server:
  port: 8000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8671/eureka


spring:
  application:
    name: spring-gateway-pr
  cloud:
    gateway:
      routes:
      - id: first-service
        uri: http://localhost:8081/
        predicates:
          - Path=/first-service/**
      - id: second-service
        uri: http://localhost:8082/
        predicates:
          - Path=/second-service/**